### ISSUE TITLE
שיפור הקשר בין מרכיבי המשחק

### ISSUE THREAD

**Issue by erelsgl** [Game-Dev-Project-D-A-Y/OceanBalance#1]
איזון כדור על משטח זה רעיון יפה, וגם איסוף בקבוקים זה רעיון יפה, אבל הקשר העלילתי ביניהם לא ברור. גם לא ברור הקשר העלילתי בין אי-אסיפת בקבוק לבין חור במשטח. הנה הצעה לפתרון שתי הבעיות:

* במקום כדור שמתגלגל - יהיה בקבוק שמתגלגל.
* בכל פעם שאוספים בקבוק - הוא עולה על המשטח ומתגלגל יחד עם האחרים.
* היעד הוא לאסוף מספר מסויים של בקבוקים ולהביא אותם לחוף תוך זמן קצוב.
* כשבקבוק נופל מהמשטח - לא נוצר חור, אלא פשוט צריך לאסוף אותו מחדש (ומפסידים זמן).

רעיון נוסף:
* כיוון שהמשחק נעשה קשה יותר ככל שאוספים יותר בקבוקים, אפשר להוסיף חוק, שאם השחקן אסף מספר מסויים של בקבוקים - באים צבי-ים ועוזרים לו (לאות תודה על כך שהציל אותם). למשל, הם שוחים ליד המשטח ומונעים מבקבוקים ליפול.

**Comment by doviec** [comment]
אחרי שדיברנו אנחנו נשפר את עניין המשטח ובצורה ויזואלית ננסה להסביר את הרעיון המשחק בצורה יותר ברורה
