### ISSUE TITLE
בדיקת 30 השניות הראשונות של המשחק

### ISSUE THREAD

**Issue by michael-lemberger** [Game-Dev-Project-D-A-Y/OceanBalance#18]
רק הערה אחת יש לי, כשהכדור נופל תתחילו את השלב מחדש, או השהמשתמש יוכל לבחור אם להתחיל מחדש.
כמובן המשחק רק בתחילתו, חסר למשחק אלמנטים מעניינים. בהצלחה בהמשך הפיתוח.

**Comment by doviec** [comment]
כמובן, המטלה הייתה על ה30 שניות הראשונות אז עוד לא הגענו לשם..

**Comment by doviec** [comment]
מעודכן אצללנו בUNITY
