### ISSUE TITLE
למה הזמן יורד?

### ISSUE THREAD

**Issue by erelsgl** [Game-Dev-Project-D-A-Y/OceanBalance#19]
כשהמשחק מתחיל, יש בקבוק על המלבן, ואין שום בקבוק בים, ובכל-זאת הזמן יורד וכשמגיע לאפס נוצר חור במלבן. לא הבנתי למה?

ראו גם את ההערות הקודמות בגיטהאב לגבי תוכן המשחק.

**Comment by doviec** [comment]
לכל בקבוק יש זמן לאסוף אותו זה הטיימר של הבקבוק,
העניין של הבקבוק הוא שאם לא הספקת לאסוף אותו, המשטח ניזוק ולכן יש חור במשטח
הבקבוק חייב להתחיל על המשטח כדי שיהיה לשחקן את האופציה לאסוף אותו בזמן ואחרת אם לא הצליח, הבקבוק יפול למים וייוצר חור במשטח כ"עונש" שלא אסף את הבקבוק
